### ISSUE TITLE
Backend featured image check doesn't stop page from publishing (in case of JS not working)

### ISSUE THREAD

**Issue by torohill** [pressupinc/require-featured-image#14]
If there is a case where the RFI Javascript fails to correctly check the featured image (for whatever reason) then the backend check (and subsequent `wp_die`) doesn't actually stop the page from being published.

Reproduction steps:

1. Set RFI to require featured images for pages.
2. Go to the edit page screen and make sure no featured image is selected.
3. The RFI error message should be displayed and the Update button should be disabled.
4. Run `jQuery('#post').submit();` in your browser console to simulate the RFI Javascript check not working.
5. You will see the backend error message (You cannot publish without a featured image.) but by this point the page is already saved and published.
6. It is now possible to view page on the frontend and it has no featured image.

Here are some possible reasons that Javascript check might not work correctly:
* RFI check logic is incorrect (this shouldn't be the case).
* there is a Javascript error which prevents executing of the RFI Javascript.
* a different plugin provides another way to submit the page for saving without using the disabled Update button.

In general, I'm not sure if you want to address this case because if the Javascript checks work correctly then this case should never happen. However, I came across this issue when creating pull request #13 and the behaviour was unexpected. I expected that the backend check would stop the page saving.

If you do want to fix this issue I think there are two case that need to be handled:
* a page that is transitioning from draft to published. In this case you could just save the page as a draft again, to make sure none of the entered content is lost, and then display the error message.
* a page is already published but the featured image is modified/removed. In this case you want to prevent the save to stop incorrect content from being displayed on the site. However, you also probably want to avoid losing any content that has been entered (eg. the user just typed a bunch of stuff in the body and probably wants to avoid typing it again). You probably don't want to set the page as draft as that will cause it to disappear from site. I'm not sure what the best solution is in this case.

**Comment by davidbhayes** [comment]
This is a very interesting bug. Thanks for finding it!

I think you're definitely right about what the process should look like for a page moving from draft to publish and I agree that the case from publish to publish is hard. I honestly hadn't thought of the risk of losing work, but that's pretty serious. Not likely to move on this immediately (other priorities, and as you said JS will prevent people hitting this in 80+% or cases) but definitely appreciate the report.

**Comment by torohill** [comment]
After some more thought maybe the best option for the publish to publish case is that all page fields other than the featured image are saved. This means that the user won't lose any content (other than the invalid featured image) and the page will still have the previous featured image, which should be valid.

**Comment by davidbhayes** [comment]
I think 2b7d49fb2720bf1772c2c18499ed9bcb304ef533 and ba94364 (listed above) should solve this. I agree with your logic @torohill for publish->publish where the image goes missing, but it requires a whole different infrastructure of catching to know what the old image was. So instead it bounces it back to a draft if that happens. As most people will see the JS (if you simply disable JS you can't actually set a featured image... 🙃) I think this is fine for the small percentage of people that will be affected.
