### ISSUE TITLE
PHP catch doesn't actually prevent post publishing

### ISSUE THREAD

**Issue by davidbhayes** [pressupinc/require-featured-image#17]
This was reported by an email correspondent. 

The code in question:

```php
add_action( 'transition_post_status', 'rfi_guard', 10, 3 );
function rfi_guard( $new_status, $old_status, $post ) {
    if ( $new_status === 'publish' && rfi_should_stop_post_publishing( $post ) ) {
        wp_die( rfi_get_warning_message() );
    }
}
```

Basically the point seems to be that the `die` the script drops happens after WordPress has made and saved the transition. 

On the topic of a solution, they said:

> I'm afraid that there is no elegant and simple solution to this problem.
> 
> The easiest thing to do is to use the same and hook, but roll back the status with another DB insert.
> 
> 
>     function transition_action($new_status, $old_status, $post) {¬
>        if ($some_condition) {
>           $postarr = $post->to_array();¬
>           $postarr['post_status'] = $old_status;¬
>           wp_insert_post($postarr, true);¬
>     }
> 
>     add_action('transition_post_status', 'transition_action', 10, 3);¬
> 
> 
> 
> 
> This is far from elegant, I'd call it horrible since it is creating more surface area for unintended side  effects.
> 
> Looking around in the source code of the WP core you can find the  pre_post_update hook. Unfortunately it only fires for updates, so it too is useless because the post status can be set on create as well as update.
> 
> The solution I'm currently working on uses the filter wp_insert_post_data, killing wordpress from there when you don't want the post to be published.
> 
> 
>     function insert_post_data_filter($data, $postarr) {
> 
>       $new_status = $postarr['post_status'];
>       
>       if (! empty( $postarr['ID'])) {
>         $old_status = get_post($postarr['ID'])->post_status;
>       }
>       else {
>         $old_status = 'new';
>       }
>       
>       // no transition took place, do nothing.
>       if ($new_status === $old_status) {
>         return $data
>       }
>       
>       if ($new_status === 'publish' && should_stop_post_publishing($postarr)) {
>         wp_die();
>       }
>       
>       return $data;
>     }
> 
>     add_filter('wp_insert_post_data', 'insert_post_data_filter', 10, 2);
> 
> 
> I'm not yet sure if this solution works, but it seems like the most promising thus far.

**Comment by etherealite** [comment]
As the author of the above quote, I much welcome any contributions or observations made in effort to solve this issue.

It seems simple, but the way the WordPress core works, it is very much biased towards the route of writing to the DB first and notifying dependant components after the write has taken place.  The result of this is that trying to subvert the DB write from a hook is like swimming upstream.

**Comment by davidbhayes** [comment]
Though I failed in my commit message, I think https://github.com/pressupinc/require-featured-image/commit/2b7d49fb2720bf1772c2c18499ed9bcb304ef533 addresses this.
